from django.core.exceptions import ValidationError


class Validations:
     
     def __init__(self):
          pass
     
     def validation(data):
          ...